### ISSUE TITLE
Update CDNJS?

### ISSUE THREAD

**Issue by evanplaice** [typeiii/jquery-csv#133]
Transferring jquery-csv to the typeiii org may or may not have broken CDNJS auto-update. CDNJS may be smart enough to follow the 304 redirect from GitHub but the reference should be updated anyway.

To fix, fork and clone<sup>1</sup> the CDNJS repo.

*<sup>1</sup> IIRC, the CDNJS repo history is massive. To prevent from downloading a ton of unnecessary history do a shallow clone of the repo `git clone --depth 5`.*

**Comment by evanplaice** [comment]
I would take care of this but seeing how libs are published to CDNJS is a very valuable learning experience.

**Comment by coltonehrman** [comment]
Have created PR to cdnjs/cdnjs repo. https://github.com/cdnjs/cdnjs/pull/13347

**Comment by evanplaice** [comment]
I enabled repo deletion, you should be able to remove the fork from the org now.

**Comment by coltonehrman** [comment]
Ok thanks 👍
