### ISSUE TITLE
v1.0.1+ triggers NPM install EISGIT error

### ISSUE THREAD

**Issue by pklauzinski** [typeiii/jquery-csv#134]
# NPM install error

NPM install results in `EISGIT` error starting with `v1.0.1`. I have verified that `v1.0.0` does not trigger this error.

## Environment

- Platform: Node 
- Version: `11.14+`

## Steps to reproduce

- Run `npm i` with `jquery-csv` as a dependency

## Expected behaviour

Should install successfully.

## Actual behaviour

```bash
npm ERR! path node_modules/jquery-csv
npm ERR! code EISGIT
npm ERR! git node_modules/jquery-csv: Appears to be a git repo or submodule.
npm ERR! git     node_modules/jquery-csv
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

**Comment by evanplaice** [comment]
In 1.0.1 the jquery-csv repo was moved to a new organization (ie changing the repo location) try uninstalling/reinstalling the package.

**Comment by pklauzinski** [comment]
> In 1.0.1 the jquery-csv repo was moved to a new organization (ie changing the repo location) try uninstalling/reinstalling the package.

Did this, and the error still occurs. I then removed my entire `node_modules` dir, ran `npm i` again, things appear to be ok, then upon a subsequent `npm i` command, the same error occurs.

Initially noticed this bug due to a build failure on CircleCI which ran from a clean install.

The error appears to happen upon running `npm` commands when the `jquery-csv` module has already been installed, even when the install was new and from the latest version.

**Comment by evanplaice** [comment]
WTF? `npm publish` was including the git metadata (ie `.git`) in the published package. That should never happen. Anyway, I fixed it and published a new version. Thank you for your patience.
