### ISSUE TITLE
isFileAPIAvailable is not defined

### ISSUE THREAD

**Issue by sebkouba** [typeiii/jquery-csv#138]
For once I'm doing some useful IT helping a doctor with Corona data...

The local file example doesn't work for me on Chrome and Safari. In the console I get the following error:

```
jQuery.Deferred exception: isFileAPIAvailable is not defined ReferenceError: isFileAPIAvailable is not defined
    at HTMLDocument.<anonymous> (http://typeiii.github.io/jquery-csv/examples/file-handling.html:41:9)

Googling hasn't helped. I'll look for a different way to handle the file since it doesn't really seem csv related but I thought I'd let you know or to find out what I'm doing wrong.
```

Cheers

edit: I see that function should be defined in helpers.js which doesn't seem to load. I'll try to figure it out...

```
Uncaught ReferenceError: global is not defined
    at helpers.js:1
(anonymous) @ helpers.js:1
```

**Comment by sebkouba** [comment]
Adding this to the top of helpers.js seems to fix the problem:
```

if (global === undefined) {
    var global = window;
  }
```

**Comment by evanplaice** [comment]
Yep. Relying on functions that map to globals (ie window/self) is a bad idea.

That's how jquery works and this lib is designed to piggy-back onto jquery's `$` namespace.

If you want a csv parser lib that doesn't use globals, check out CSV-ES. It's a ground-up rewrite of jquery-csv designed w/ more modern best practices in mind.
